import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./comonents/navbar/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500`}
      >
        <NavBar/>
        <div className=" pt-24">
        {children}
        </div>
      </body>
    </html>
  );
}
